package socket_server.domain.game.util;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

public class WordUtils {

    public static List<String> ENG_WORDS = List.of(
            "aircraft carrier",
            "airplane",
            "alarm clock",
            "ambulance",
            "angel",
            "apple",
            "arm",
            "axe",
            "backpack",
            "banana",
            "bandage",
            "baseball",
            "basketball",
            "bat",
            "bathtub",
            "bed",
            "bee",
            "bicycle",
            "bird",
            "birthday cake",
            "book",
            "bowtie",
            "bread",
            "broom",
            "bucket",
            "bus",
            "bush",
            "butterfly",
            "cake",
            "calendar",
            "camera",
            "campfire",
            "candle",
            "car",
            "carrot",
            "cat",
            "cell phone",
            "chair",
            "church",
            "circle",
            "cloud",
            "compass",
            "computer",
            "cookie",
            "couch",
            "cow",
            "crab",
            "crocodile",
            "crown",
            "cup",
            "dog",
            "dolphin",
            "donut",
            "door",
            "duck",
            "ear",
            "elephant",
            "envelope",
            "eye",
            "eyeglasses",
            "face",
            "fan",
            "fire hydrant",
            "fish",
            "flower",
            "fork",
            "frog",
            "frying pan",
            "garden",
            "giraffe",
            "grapes",
            "guitar",
            "hammer",
            "hat",
            "helicopter",
            "hexagon",
            "hockey stick",
            "horse",
            "ice cream",
            "jacket",
            "kangaroo",
            "keyboard",
            "knife",
            "ladder",
            "laptop",
            "leaf",
            "leg",
            "lighthouse",
            "lightning",
            "lion",
            "lobster",
            "lollipop",
            "mailbox",
            "map",
            "marker",
            "megaphone",
            "moon",
            "motorbike",
            "mountain",
            "mug");

    public static final List<String> KOR_WORDS = List.of(
            "항공모함",
            "비행기",
            "알람시계",
            "앰뷸런스",
            "천사",
            "사과",
            "팔",
            "도끼",
            "백팩",
            "바나나",
            "붕대",
            "야구공",
            "농구공",
            "야구배트",
            "욕조",
            "침대",
            "꿀벌",
            "자전거",
            "새",
            "생일케이크",
            "책",
            "나비넥타이",
            "빵",
            "빗자루",
            "양동이",
            "버스",
            "수풀",
            "나비",
            "케이크",
            "달력",
            "카메라",
            "모닥불",
            "양초",
            "차",
            "당근",
            "고양이",
            "핸드폰",
            "의자",
            "교회",
            "동그라미",
            "구름",
            "컴파스",
            "컴퓨터",
            "쿠키",
            "소파",
            "소",
            "게",
            "악어",
            "왕관",
            "컵",
            "개",
            "돌고래",
            "도넛",
            "문",
            "오리",
            "귀",
            "코끼리",
            "편지봉투",
            "눈",
            "안경",
            "얼굴",
            "선풍기",
            "소화기",
            "물고기",
            "꽃",
            "포크",
            "개구리",
            "프라이팬",
            "정원",
            "기린",
            "포도",
            "기타",
            "망치",
            "모자",
            "헬리콥터",
            "육각형",
            "하키 채",
            "말",
            "아이스크림",
            "재킷",
            "캥거루", "키보드", "칼", "사다리", "노트북", "나뭇잎", "다리", "등대", "번개", "사자", "가재", "막대사탕", "우체통", "지도", "보드마카", "확성기", "달", "오토바이", "산", "머그컵");

    private static final Random random = new Random();

    public static List<Integer> getRandomIndexes(int n) {
        if (n > ENG_WORDS.size()) {
            throw new IllegalArgumentException("단어 개수 n이 WORDS 크기보다 클 수 없습니다.");
        }

        List<Integer> indexes = new ArrayList<>();
        for (int i = 0; i < ENG_WORDS.size(); i++) {
            indexes.add(i);
        }

        Collections.shuffle(indexes, random);
        return indexes.subList(0, n);
    }

    public static String getEngWord(int index) {
        return ENG_WORDS.get(index);
    }

    public static String getKorWord(int index) {
        return KOR_WORDS.get(index);
    }
}
