spring:
  datasource:
    url: jdbc:mysql://${PERF_DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${PERF_DATABASE_NAME:gotcha}
    username: ${PERF_DATABASE_USER:root}
    password: ${PERF_DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

csrf:
  cookie:
    secure: false